### ISSUE TITLE
Whats after ./install.sh

### ISSUE THREAD

**Issue by rohybnol** [khaleghsalehi/ironfox#1]
It completed and told me:
Please create a user and set password for it by:
bash 1- sudo su - postgres
psql 2- createuser --interactive --pwprompt
psql 3- create databses ironfox;
bash 4- sudo systemctl start innovera
setup done.

All done properly altough I do not understand where I put my backed IP which is used for protection and how to make it work as when I go to my VPS wherw I installed your script on https://IP nothing happen, I am using the ubuntu version you recommended the only difference I did was to start the installer.sh using bash installer.sh instead of ./installer but that shouldn't be the issue? Thanks man!

**Comment by khaleghsalehi** [comment]
All settings are done in the IronFox web dashboard. By default, the dashboard is available via http://127.0.0.1:8080, and you can see the necessary information from the link below, and everything is specified in the code.
https://github.com/khaleghsalehi/ironfox/blob/master/manager/application.properties


You can change the settings in this file as follows:
server.address=<your_ip>
server.port=<your_port>

https://stackoverflow.com/questions/23946369/how-to-configure-embedded-tomcat-integrated-with-spring-to-listen-requests-to-ip

**Comment by rohybnol** [comment]
sadly I still couldn't get it to run:
```
==========================================
please flow up below command:
please create a user and set password for it by:
bash 1- sudo su - postgres
psql 2- createuser --interactive --pwprompt
psql 3- create databses ironfox;
bash 4- sudo systemctl start innovera
setup done.
root@server:~/ironfox-0.1# sudo su - postgres
postgres@server:~$ createuser --interactive --pwprompt
Enter name of role to add: admin
Enter password for new role: admin
Enter it again: admin
Shall the new role be a superuser? (y/n) y
postgres@server:~$ createdb ironfox;
postgres@server:~$ sudo systemctl start innovera
[sudo] password for postgres: admin
Sorry, try again.
[sudo] password for postgres: admin
sudo: 1 incorrect password attempt

also:
root@server:~/ironfox-0.1# curl http://127.0.0.1:8080
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
```
I followed your tutorial accordingly still couldn't get it to run it says password for postgres is wrong even i type the exact same password "admin" 
thanks very much

**Comment by khaleghsalehi** [comment]
It's seems dashboard (web ui)  is not started. please share more information.

**Comment by rohybnol** [comment]
It says incorrect password for postgres? Check the log i posted above

**Comment by khaleghsalehi** [comment]
https://sysadminxpert.com/how-to-install-postgresql-12-on-ubuntu/
