### ISSUE TITLE
ubuntu 18.04 no pass

### ISSUE THREAD

**Issue by w796933** [khaleghsalehi/ironfox#1]
sir   ubuntu 18.04  run ./install.sh no pass  

![微信图片_20201114165546](https://user-images.githubusercontent.com/4869179/99143731-bf39fe00-269a-11eb-97ca-942d984afe9c.png)

**Comment by khaleghsalehi** [comment]
create user "ironfox". 
e.g
khalegh@KhaleghHomePc:~$ createuser  ironfox

**Comment by khaleghsalehi** [comment]
fixed and committed  [here](https://github.com/khaleghsalehi/ironfox/commit/7af0b186b4871e0f806bd5df4de13259f144d94e)

**Comment by w796933** [comment]
install.sh  script   why is disable   postgresql ?  and anto  create  database ?

**Comment by khaleghsalehi** [comment]
Actually it's belong for[ ironfox panel.](https://github.com/khaleghsalehi/panel)
at line 6 to 8 [here](https://github.com/khaleghsalehi/panel/blob/master/src/main/resources/application.properties) 

Current panel developed nightly with java ( spring boot), maybe moved to c and part of ironfox code base in the future.
if you want to figure out panel db manually [please setup PostgreSQL 12 with below entry:

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ironfox
spring.datasource.username=sp
spring.datasource.password=123456

**Comment by w796933** [comment]
sir, install.sh  script support  auto install postgresql ?
and  auto inport database ?

**Comment by khaleghsalehi** [comment]
actually no, but you can figure out PostgreSql manually, please flow up below link.
https://computingforgeeks.com/install-postgresql-12-on-ubuntu/
