### ISSUE TITLE
How does Anomaly detection work?

### ISSUE THREAD

**Issue by goldpower** [khaleghsalehi/ironfox#10]
How does Anomaly detection work?
Please explain step by step .

**Comment by khaleghsalehi** [comment]
Hack the codes below, everything is clear:
https://github.com/khaleghsalehi/ironfox/blob/master/modules/ngx_http_bot_protection_module/src/ngx_http_bot_protection_module.c

1- The first request is considered a valid and legal request.
2- In response to the first request, the encrypted token is given to the client (suppose something like JWT)
3- In the second request, the client must resend his/her identity along with the encrypted token
4- If they are the same, the request will be accepted and if they are not the same, the request will be rejected.

**Comment by goldpower** [comment]
These steps can be easily done by a bot !!!   (step 1 to 4 )
