### ISSUE TITLE
Unable to log in to the panel console.

### ISSUE THREAD

**Issue by ne0ke718** [khaleghsalehi/ironfox#16]
I configured `ironfox.username` and `ironfox.password` in the `application.properties` file. As shown below:

ironfox.username=ironfox
ironfox.password=test1234

However, after entering the correct username, password, and key in the panel console, I am unable to log in successfully.

**Comment by ne0ke718** [comment]
Oct 29 02:40:15 dnstest runservice.sh[15917]: 2024-10-29 02:40:15.470  INFO 15927 --- [         task-1] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect
Oct 29 02:40:16 dnstest runservice.sh[15917]: 2024-10-29 02:40:16.407  INFO 15927 --- [         task-1] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction
Oct 29 02:40:16 dnstest runservice.sh[15917]: 2024-10-29 02:40:16.416  INFO 15927 --- [         task-1] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
Oct 29 02:40:16 dnstest runservice.sh[15917]: 2024-10-29 02:40:16.877  INFO 15927 --- [           main] DeferredRepositoryInitializationListener : Spring Data repositories initialized!
Oct 29 02:40:16 dnstest runservice.sh[15917]: 2024-10-29 02:40:16.886  INFO 15927 --- [           main] org.ironfox.panel.PanelApplication       : Started PanelApplication in 5.53 seconds (JVM running for 5.977)
Oct 29 02:40:16 dnstest runservice.sh[15917]: 2024-10-29 02:40:16.888  INFO 15927 --- [           main] org.ironfox.panel.PanelApplication       : successfully wrote raw config file.
Oct 29 02:40:16 dnstest runservice.sh[15917]: 2024-10-29 02:40:16.930  WARN 15927 --- [           main] org.ironfox.panel.PanelApplication       : ironfox not configured yet
Oct 29 02:41:04 dnstest runservice.sh[15917]: 2024-10-29 02:41:04.463  INFO 15927 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
Oct 29 02:41:04 dnstest runservice.sh[15917]: 2024-10-29 02:41:04.463  INFO 15927 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
Oct 29 02:41:04 dnstest runservice.sh[15917]: 2024-10-29 02:41:04.470  INFO 15927 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms

**Comment by ne0ke718** [comment]
Additionally, could you explain how the plaintext Iron.js is obfuscated into the ciphertext in iron.js? I need to make some modifications to the code in Iron.js, but after making the changes, I don't know how to obfuscate it back into the obfuscated code in iron.js.

**Comment by khaleghsalehi** [comment]
try link below, it's work:
https://obfuscator.io/

**Comment by khaleghsalehi** [comment]
Oct 29 02:40:16 dnstest runservice.sh[15917]: 2024-10-29 02:40:16.930 WARN 15927 --- [ main] org.ironfox.panel.PanelApplication **: ironfox not configured yet**
