### ISSUE TITLE
sadly I still couldn't get it to run:

### ISSUE THREAD

**Issue by rohybnol** [khaleghsalehi/ironfox#2]
sadly I still couldn't get it to run:
```
==========================================
please flow up below command:
please create a user and set password for it by:
bash 1- sudo su - postgres
psql 2- createuser --interactive --pwprompt
psql 3- create databses ironfox;
bash 4- sudo systemctl start innovera
setup done.
root@server:~/ironfox-0.1# sudo su - postgres
postgres@server:~$ createuser --interactive --pwprompt
Enter name of role to add: admin
Enter password for new role: admin
Enter it again: admin
Shall the new role be a superuser? (y/n) y
postgres@server:~$ createdb ironfox;
postgres@server:~$ sudo systemctl start innovera
[sudo] password for postgres: admin
Sorry, try again.
[sudo] password for postgres: admin
sudo: 1 incorrect password attempt

also:
root@server:~/ironfox-0.1# curl http://127.0.0.1:8080
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
```
I followed your tutorial accordingly still couldn't get it to run it says password for postgres is wrong even i type the exact same password "admin" 
thanks very much

_Originally posted by @rohybnol in https://github.com/khaleghsalehi/ironfox/issues/1#issuecomment-980707070_

**Comment by rohybnol** [comment]
also is it possible to access the panel with http://public_ip:8080 instead of http://127.0.0.1:8080?

**Comment by khaleghsalehi** [comment]
also is it possible to access the panel with http://public_ip:8080 instead of http://127.0.0.1:8080?

**Sure,**

**Comment by rohybnol** [comment]
How?

**Comment by khaleghsalehi** [comment]
at https://github.com/khaleghsalehi/ironfox/blob/master/manager/application.properties

server.address=<your_ip>
server.port=<your_port>

**Comment by rohybnol** [comment]
The panel does not start for me it crashes after creating hikaripool then big crash message :(

**Comment by khaleghsalehi** [comment]
send me more information (Log) please.
